### ISSUE TITLE
Is it necessary to install Windows ADK with W10MUI

### ISSUE THREAD

**Issue by anwar-alsilwy** [abbodi1406/BatUtil#10]
Last time, I rebuilt install.wim using W10MUI to integrate multiple languages ( En,Fr,Ar), but without installing Windows ADK packages !!
It's working successfully, but I read on description that Windows ADK is requirement for this process  !!
Is it really necessary or I miss something ??

**Comment by abbodi1406** [comment]
Nothing has changed
Windows ADK is only required if you want the Standard WinPE localization (for boot.wim/winre.wim), or you want to install **Updates** after language packs

**Comment by anwar-alsilwy** [comment]
So, I don't need ADK , because I asked you about language pack, you told me to update install.wim first from Windows update catalog, then install multiple languages using W10MUI
Am I right ??

**Comment by anwar-alsilwy** [comment]
So, I don't need ADK , because I asked you about language pack, you told me to update install.wim first from Windows update catalog, then install multiple languages using W10MUI
Am I right ??

**Comment by abbodi1406** [comment]
Language packs first, then updates (optional)

if install.wim already contain updates, then you must re-add updates (or integrate new updates)

**Comment by anwar-alsilwy** [comment]
Thanks for correcting me
