### ISSUE TITLE
YAOCTRIR freezes

### ISSUE THREAD

**Issue by Orvis** [abbodi1406/BatUtil#12]
Hello,
I use YAOCTRIR to manage the Office installation of an unattended installer for Win 10. I only use the Office part of the YAOCTRIR installer and I couple it with NTLite.
NTLite installs Win 10 and the setup cmd calls YAOCTRIR installer for Office installation.

It launches the Office installation well, but when it reaches around 60%-70%, the installer gets stuck and nothing happens. I waited for 30 minutes and nothing happens. If I close the command window, the install process of Windows is finalized, the PC reboots and everything is fine. Win 10 is correctly installed, and Office too.

So how can I get rid of this freeze ?
Thanks.

**Comment by abbodi1406** [comment]
Share *.log files from `C:\Windows\Temp` may help tracking the cause
