### ISSUE TITLE
An idea about ESD converter

### ISSUE THREAD

**Issue by michelle1574** [abbodi1406/BatUtil#13]
Hello, I have an message, about the ESD converter.
Ideas:
1. It should be programmed like UUP converter
2. When detected more editions allow to choose (for example Pro and Enterprise) instead of Home, Home N, Pro N and Home Single language.
3. And also, when detected multiple architectures and or editions show all detected.
4. Add configuration options (SkipISO, CreateESD) (SkipISO is for not creating iso, saving the folder and CreateESD creates the install.esd instead of install.wim).
Thank you!
Michelle1574

**Comment by abbodi1406** [comment]
- I'm not sure i understand what you mean, the script already allow to choose from multi editions
- multi-architecture feature is limited by design, expanding it will require alot of recoding

thanks for the suggestions, i will try to incorporate the improvements

**Comment by michelle1574** [comment]
> 
> 
>     * I'm not sure i understand what you mean, the script already allow to choose from multi editions
> 
>     * multi-architecture feature is limited by design, expanding it will require alot of recoding
> 
> 
> thanks for the suggestions, i will try to incorporate the improvements

Ok, I'm waiting. So, I'm curious about creating UUP downloader (1 try: from MS, 2 try: from user's files (archive.org, etc))

**Comment by abbodi1406** [comment]
esd-decrypter v63 should be close enough

**Comment by michelle1574** [comment]
Sorry if I wasted your time, but also I want to inform to program detect all ESD's at once and process all ESD's if more detected.

**Comment by abbodi1406** [comment]
You can edit decrypt.cmd and replace this line `choice /c 0 /n` with `exit /b`
then, set `AutoStart` option as desired, and run the script from comand prompt (or another script) calling it for all the ESDs you want to process
e.g.
```
call decrypt.cmd 22000.318.211104-1236.co_release_svc_refresh_CLIENTBUSINESS_VOL_x64FRE_en-us.esd
call decrypt.cmd 22000.318.211104-1236.co_release_svc_refresh_CLIENTCONSUMER_RET_x64FRE_en-us.esd
```
