### ISSUE TITLE
new languages vi-vn id-id error

### ISSUE THREAD

**Issue by angelics** [abbodi1406/BatUtil#14]
hi,
im trying to add vi-vn, id-id.
using 22621.3 en-us, latest mui

ERROR: Microsoft-Windows-Client-LanguagePack-Package_id-id-amd64-id-id.esd is not a valid Windows NT 10.0 LangPack

**Comment by angelics** [comment]
after some try, im able to continue without error.
changed line 221 `"!_7z!" e ".\langs\!LPFILE%%j!" -o"!EXTRACTDIR!" Microsoft-Windows-Common-Foundation-Package*10.*.mum %_Nul3%` to  `"!_7z!" e ".\langs\!LPFILE%%j!" -o"!EXTRACTDIR!" Microsoft-Windows-CoreSystem-DISM-Package*10.*.mum %_Nul3%`

**Comment by stdin82** [comment]
W10MUI only support full languages
