### ISSUE TITLE
Windows 10 22H2 build 19045 language packs

### ISSUE THREAD

**Issue by MaherFa** [abbodi1406/BatUtil#15]
I tried using LP from 19041-LPs.txt, it integrated successfully using NTLite but after installing windows it kept restarting then failed to start the final setup.

will there be new links for 19045?

**Comment by abbodi1406** [comment]
Add or readd latest Cumultive Update after LP
there are no new LPs or FODs, all 1904x builds use 19041 files, and the Cumultive Update adds the new files

**Comment by MaherFa** [comment]
thanks, I'll try your suggestion.
