### ISSUE TITLE
Windows 8.1 Update 3 x86 - Setup Cannot Continue Due to a Corrupt Installation File

### ISSUE THREAD

**Issue by dribgnikcom** [abbodi1406/BatUtil#21]
Steps to reproduce:

Obtain `en_windows_8.1_with_update_x86_dvd_6051550.iso`

Obtain `WHDownloader 0.0.2.4`

Download all updates under `Windows8.1-Update3-x86` Update List

Run WHD-W81UI.cmd (version 7.0) with the following options:

LDR: Yes
Hotfixes: Yes
WU satisfy: Yes
WMF: Yes
Enable .NET 3.5: Yes
Cleanup System Image: Yes
Reset Base: Yes

The setup moves along to the second stage where it copies the files, and then throws the error in the title of this issue.

Thanks

**Comment by abbodi1406** [comment]
Did WHD-W81UI.cmd updating progress had any errors?

**Comment by dribgnikcom** [comment]
No sir, not that I saw.  I can run it again in debug mode if you like.  Give me a little time please.

**Comment by dribgnikcom** [comment]
Yes!  There is a single error.

`Processing 30 of 31 - Adding package Package_for_RollupFix~31bf3856ad364e35~x86~~9600.20821.1.18
Package_for_RollupFix: The specified image is no longer serviceable and may be corrupted. 
Discard the modified image and start again.
 Error: 0x8007007f
Processing 31 of 31 - Package_for_KB5023819: The specified image is no longer serviceable and may be corrupted. 
Discard the modified image and start again.
 Error: 0x800f0830

Error: 127

The specified image is no longer serviceable and may be corrupted. 
Discard the modified image and start again.
The command completed with errors. 
For more information, refer to the log file.

The DISM log file can be found at C:\Windows\Logs\DISM\dism.log`

Please see attached log.
[WHD-W81UI_Debug.log](https://github.com/abbodi1406/BatUtil/files/10787970/WHD-W81UI_Debug.log)

**Comment by abbodi1406** [comment]
> Yes! There is a single error.

Thanks
do you still have dism.log too? if so, 7-zip and attach (or use external host if not possible)

**Comment by abbodi1406** [comment]
Nevermind, i found the culprit
you are using v7.0 of the script, it does not support ESU updates (2023-02 updates and later are blocked for Win8.1 Client)
v7.1 should hand;e integration correctly:
[WHD-W8.1UI_7.1.zip](https://github.com/abbodi1406/WHD/raw/master/scripts/WHD-W8.1UI_7.1.zip)

i forgot to upload here to BatchUtil, now it's updated

**Comment by dribgnikcom** [comment]
Thank you very much.  I really appreciate it.
