### ISSUE TITLE
Merging the Multilanguage thing with UUP >>WIM/ISO conventer

### ISSUE THREAD

**Issue by michelle1574** [abbodi1406/BatUtil#23]
The UUP>>ISO conventer would have the full option which is (Ability to choose in the installer the language) but UUP>>WIM would have the Mini function
Btw can you ask UUPDump to make that in their webpage so you can make it easier?

**Comment by abbodi1406** [comment]
No for complications

**Comment by michelle1574** [comment]
Then why uup.rg-adguard.net made it?

**Comment by michelle1574** [comment]
And what about putting the multilingual maker cmd file to the UUP-wimlib and adding a few lines to the ini file and modyfiying the CMD programs.
If VirtualEditions is turned on as well, then
1. UUP > ISO
2. Virtual Editions
3. Multilingual
4. Create ISO

**Comment by abbodi1406** [comment]
UUP dump is designed to handle one language per edition(s) (and that's based on MS aggregated metadata)
