### ISSUE TITLE
2 feature requests regarding esd iso 1. have the ability to convert multipul esds in a folder. 2. delete source esd after convertion

### ISSUE THREAD

**Issue by mhussaincov93** [abbodi1406/BatUtil#25]
hi Abbodi,
would it be possible to add the folowing features?
the ability to delete the source .esd after conversion is complete?
I believe this would be very handy.
if it were set as a configurable setting it would be great!
2.
the ability to convert multipul esds one after another.
example.
I have a few .esds in the folder.
c:\esds
when esd>iso detects the esds,
it would ask the usual questions and use the answered questions to bulk create the isos or .wim etc.
one after another.
I would be greatful if you would considder this request.
Majid Hussain

**Comment by abbodi1406** [comment]
For 1, it's not reliable option, it's best to keep the ESD files in case you need them or conversion failed
it's not hard to manually delete them

For 2:
- download: https://github.com/abbodi1406/BatUtil/raw/master/esd-decrypter-wimlib/decrypt.cmd
- set `AutoStart` option as needed
- run command prompt as administrator
- call the script with each ESD file name, example:
`decrypt.cmd 15063.0.170317-1834.rs2_release_cliententerprise_vol_x86fre_en-us_dc818e39982d8bd922dca73fd51e330aa99bc3f1.esd`

you can create another script and add all the ESDs you want to convert, example:
```
decrypt.cmd 1.esd
decrypt.cmd 2.esd
decrypt.cmd 3.esd
decrypt.cmd 4.esd
```
