### ISSUE TITLE
esd decrypter not able to select multiple esd files (when it is like Pro.esd, HomeN.esd, etc)

### ISSUE THREAD

**Issue by michelle1574** [abbodi1406/BatUtil#26]
gus33000 made a project ESD-Decrypter which allowed you to convert multiple ESD's to ISO's. It was archived and there is nothing to do with it.
So here are all the features I want to add:
1.	GUI
2.	Multiple ESD choice when detected
3.	ISO naming formats
4.	Edition selecting when there are 2 ESD’s that have multiple editions (e.g., first one has Pro, Pro N, Home, Home N and Home Single Language and second has Pro, Pro N, Enterprise, Enterprise N, Education, Education N)
5.	Choice to compile in ESD or WIM
6.	ESD Downloading and finding on MS file database
7.	Automatic recording option (to DVD and to USB) after creating ISO
8.     Saving to different folder/disk
Not all the features need to be added.
And here you can find ESD files: https://files.rg-adguard.net/version/f0bd8307-d897-ef77-dbd6-216fefbe94c5
So for 4. when there was older builds, you had to download each edition (so Pro.esd, Home.esd, ProN.esd, HomeN.esd)

**Comment by abbodi1406** [comment]
I'm not Microsoft to implement all of that
this one would give you some
https://github.com/AveYo/MediaCreationTool.bat

**Comment by michelle1574** [comment]
I mean like 1507 it has split ESD files into editions (Home.esd, HomeN.esd) and not Consumer.esd

**Comment by abbodi1406** [comment]
I know, but it's not like you are going to do the conversion multiple times
effort from the end user is not much
the automation you are looking for, require programming skills
