### ISSUE TITLE
ERROR: required file cleanospp.exe is missing

### ISSUE THREAD

**Issue by Lihnor** [abbodi1406/BatUtil#29]
Happens while trying to use Office scrubber, appears just after executing. Tried searching where to locate this file to put it but had no luck

**Comment by abbodi1406** [comment]
Redownload, i forgot to update the script
or download the ready pack:
https://github.com/abbodi1406/WHD/raw/master/scripts/OfficeScrubber_11.7z

**Comment by Lihnor** [comment]
Yup now it works, thanks
