### ISSUE TITLE
plz add virtual version support

### ISSUE THREAD

**Issue by adavak** [abbodi1406/BatUtil#3]
ProfessionalCountrySpecific

and

ProfessionalSingleLanguage

Thanks.

**Comment by abbodi1406** [comment]
They are not official editions, and cannot be activated normally

**Comment by adavak** [comment]
plz help look the pull requests string was correct? i will using by my self.
(label not offical only i guess)

Thanks.

**Comment by abbodi1406** [comment]
Looks
but like i said, i won't add support for these editions currently
you are free to use your modified script

**Comment by adavak** [comment]
Okey closed.
