### ISSUE TITLE
Questions about uupdump.net that not related to the `BatUtil` project.

### ISSUE THREAD

**Issue by codenamedpkt** [abbodi1406/BatUtil#31]
I generated the following URL with AgentGPT for listing all of latest builds with following:

https://uupdump.net/fetchupd.php?arch=arm64;amd64&flight=Mainline&ring=Canary;Dev;Beta;ReleasePreview&build=latest;22631.1

https://uupdump.net/fetchupd.php?arch=arm64,amd64&flight=Mainline&ring=Canary,Dev,Beta,ReleasePreview&build=latest,22631.1

And gets errors message with following scrnshot:

> ![Screenshot_20231111_005358_Chrome](https://github.com/abbodi1406/BatUtil/assets/23336645/9dece85b-b643-4da5-9d50-78e12bbeaf5d)
> The URL parameter options separated with commas (,).

> ![Screenshot_20231111_005502_Chrome](https://github.com/abbodi1406/BatUtil/assets/23336645/a481566e-9964-4f40-b265-529e01bc9df4)
> The URL parameter options separated with semicolons (;).

Any mistakes taken in my URL provided?

**Comment by abbodi1406** [comment]
https://git.uupdump.net/uup-dump/containment-zone/src/branch/master/FAQ.md#i-want-to-retrieve-some-data-from-uup-dump-in-an-automatic-manner

list 23H2
https://api.uupdump.net/listid.php?search=22631
Dev
https://api.uupdump.net/listid.php?search=regex:(2[3-4]\d{3})\.[1-9]
Canary
https://api.uupdump.net/listid.php?search=regex:(2((2(?!000|6[2-4][1-9])\d{3})|(5(?!398)\d{3})|[6-9]\d{3}))\.[1-9]|([3-9]\d{4})\.[1-9]
detect latest 23H2
https://api.uupdump.net/fetchupd.php?arch=all&ring=ReleasePreview&build=22631.1
