### ISSUE TITLE
W10MUI is not working (but it should)

### ISSUE THREAD

**Issue by michelle1574** [abbodi1406/BatUtil#32]
Since it has a debug log, I'm posting it here:
[W10MUI_Debug.log](https://github.com/abbodi1406/BatUtil/files/13749023/W10MUI_Debug.log)

**Comment by michelle1574** [comment]
Also, I've been trying the latest version as well (the same error)

**Comment by abbodi1406** [comment]
LanguageFeatures cab files should be placed inside `\OnDemand\x64` folder, not `\Langs`

**Comment by michelle1574** [comment]
Okay. I'll do it then.

**Comment by abbodi1406** [comment]
Read the text files and download the required files
don't just blindly place whatever files you get from uup and expect the script to magically work
