### ISSUE TITLE
UUp => ISO 100

### ISSUE THREAD

**Issue by asterix4you** [abbodi1406/BatUtil#35]
![image](https://github.com/abbodi1406/BatUtil/assets/9692180/a069f77b-8ddd-41c9-a46e-6d235737f175)

26058.1100_amd64_it-it_professional_f5822673_convert_virtual

convert-UUP v100

=== Adding Apps . . .

Microsoft.NET.Native.Framework.x64.2.2
Microsoft.NET.Native.Runtime.x64.2.2
Microsoft.Services.Store.Engagement.x64
Microsoft.UI.Xaml.x64.2.7
Microsoft.UI.Xaml.x64.2.8
Microsoft.VCLibs.x64.14.00
Microsoft.VCLibs.x64.14.00.Desktop
Microsoft.WindowsAppRuntime.x64.1.3
Microsoft.WindowsStore_8wekyb3d8bbwe
La chiamata di procedura remota non è riuscita. 
error ....

**Comment by abbodi1406** [comment]
It's known issue since build 26040
no fix available yet
you need to run conversion on Canary build host OS (25xxx or later)
or download ready iso from Insider downloads

**Comment by asterix4you** [comment]
Download V101 ?
