### ISSUE TITLE
OfficeScrubber unattended run

### ISSUE THREAD

**Issue by ixeldino** [abbodi1406/BatUtil#36]
I need to install Office LTSC with my config and remove all instaled versions automaticaly. But [OfficeScrubber_11.7z](https://github.com/abbodi1406/WHD/blob/master/scripts/OfficeScrubber_11.7z) need user choice and not has any params to run it unattended. Or its not documented yet. Please add unatended mode to run RemoveAll without user choice.

**Comment by abbodi1406** [comment]
v12
```
/P  
Scrub Office UWP

/C  
Scrub Office C2R

/M6  
Scrub Office 2016 MSI

/M5  
Scrub Office 2013 MSI

/M4  
Scrub Office 2010

/M2  
Scrub Office 2007

/M1  
Scrub Office 2003

/A  
Scrub ALL
```
