### ISSUE TITLE
[W7MUI] RTM version?

### ISSUE THREAD

**Issue by thepwrtank18** [abbodi1406/BatUtil#37]
From what I heard, you need to install language packs for Windows 7 _before_ you install Service Pack 1, otherwise it cancels out and then you have to install them again. Can I use this for RTM versions of Windows 7?

**Comment by abbodi1406** [comment]
Refresh LangPack KB2483139 support both RTM & SP1

the script only work and tested for SP1 source
however, you can try for RTM source, but you need to edit it as follows:
search and replace all occurrences of `sp1\` with none

**Comment by thepwrtank18** [comment]
Do I replace all occurrences of `\sp1` too?

**Comment by thepwrtank18** [comment]
Doesn't work, DISM simply spams "The specified package is not applicable to this image."

**Comment by abbodi1406** [comment]
I see
then you should try old LPs
but you have to edit the script and delete this line:
`if not exist "!EXTRACTDIR!\*.mum" set ERRFILE=!LPFILE%%j!&goto :E_SP1`

yes, all occurrences of `\sp1`
