### ISSUE TITLE
[W7MUI] Feature request - Warn if anything else is using DISM at the moment

### ISSUE THREAD

**Issue by thepwrtank18** [abbodi1406/BatUtil#38]
I had an issue where I was using NTLite and W7MUI at the same time (for different WIM files). NTLite unmounts every image when it's done (it doesn't outright say it, so you don't know until it happens), so that caused issues for W7MUI. I suggest giving a warning if anything else is using DISM to prevent conflicts.

**Comment by abbodi1406** [comment]
Would not that be a NTLite issue?
i don't think batch script should be that elegant :grin:
