### ISSUE TITLE
add modifications of FoD list like UWP 

### ISSUE THREAD

**Issue by ionuttbara** [abbodi1406/BatUtil#40]
windows comes with fod which can be removed using dism
fod are optional on demand feature, features which can be added/removed to image. 
how to find a fod? its easy in uupdump you have .cab files generated. can be all by default of none. all depends by custom configs just like lists microsoft store apps

**Comment by abbodi1406** [comment]
You mean uup-converter?
store apps are not built-in, they can be added or skipped
FOD packs are prebuilt, they can't be customized to pick and choose, all the default FODs are required for successful conversion to install.wim

and no, i have no plans to add manual FOD removal to uup-converter

**Comment by ionuttbara** [comment]
yes. after all install.wim is built, it will be able to remove fod with dism.
https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/features-on-demand-v2--capabilities?view=windows-11
for more infos.
in 24h2 there are more FoDs because the movement from Optional Features to FoD is more than half.

**Comment by abbodi1406** [comment]
I understand, but up-converter is not customization or nliting utility
