### ISSUE TITLE
SkipEdge option doesn't work on Windows 11

### ISSUE THREAD

**Issue by eccoisle** [abbodi1406/BatUtil#42]
Using uupdump.net and the uup_download_windows command script.

I've ensured that AddUpdates=1 is set before attempting to change this option, but both values (1, 2) have no effect on the resulting Windows install, with Edge present on the system. Setting SkipEdge = 1 and installing Windows 10 seems to work, so I'd suggest you add a note in the ReadMe.html to let users know that the feature isn't compatible with Windows 11.

Thanks!

**Comment by abbodi1406** [comment]
`SkipEdge = 1` only works for Windows 10 builds 17134-19045, or Windows 11 build 26052 and later
`SkipEdge = 2` only have effect for Windows 10 builds 17134-19045, but it may not work

**Comment by eccoisle** [comment]
Thanks for the reference – would you consider adding this to the ReadMe so that other people are aware of the compatible Windows versions? Thank you!
