### ISSUE TITLE
[W7MUI] Taiwan (zh-tw) langpacks?

### ISSUE THREAD

**Issue by thepwrtank18** [abbodi1406/BatUtil#43]
Just wondering if zh-tw langpacks are supported. They were never made in .exe files by themselves, only .iso's with .cab files inside.

https://archive.org/download/windows-7-mui-all-language-packs-sp0-sp1-x86-x64/zh-tw_windows_7_sp1_language_pack_x86_dvd_619609.iso
https://archive.org/download/windows-7-mui-all-language-packs-sp0-sp1-x86-x64/zh-tw_windows_7_sp1_language_pack_x64_dvd_646888.iso

**Comment by abbodi1406** [comment]
Yes, the script can handle exe or cab files (so you have to extract it from iso)
