### ISSUE TITLE
[convert-UUP.cmd] Feature Request: optionally allow configuring offline international settings.

### ISSUE THREAD

**Issue by JaiChoccyFox** [abbodi1406/BatUtil#46]
Not an issue, this is more of a feature request and QoL/convenience feature for the UUP converter script. Setting offline international settings with DISM commands such as `/Set-UserLocale`, `/Set-SysLocale`, `/Set-InputLocale`, and `/Set-TimeZone` is handy for users who are located in specific countries/timezones.

For example, as someone located in Australia, I'd download the en-GB images which gives us the correct localisation (as we use British English.) However, the en-GB images have defaults which aren't entirely suitable for Australia. Notably the keyboard layout defaults to UK which is incorrect as Australia uses the US keyboard layout, among other unsuitable defaults like the timezone being UTC. This is prominent when booting into the **winre.wim** recovery environment where the keyboard layout will always default to UK in this case, making Command Prompt slightly annoying to use should one have to use it.

**Comment by abbodi1406** [comment]
I think that would be handled easier with answer files (auto/unattend.xml)

i could add support for adding that file
