### ISSUE TITLE
[W10UI] Unable to integrate update 22631.4541 from UUP

### ISSUE THREAD

**Issue by xrgzs** [abbodi1406/BatUtil#49]
Starting from 22631.4541, the format of LCU on UUP has changed from CAB+PSF to WIM+PSF, which W10UI cannot recognize and integrate.

[Windows 11, version 23H2 (22631.4541) amd64](https://uupdump.net/findfiles.php?id=f3691231-0586-44d5-859b-e25f5eb9cfb7&q=!updates)

| File                                                        | SHA-1                                    | Size       |
| ----------------------------------------------------------- | ---------------------------------------- | ---------- |
| DesktopDeployment.cab                                       | ee9fc96527aa114bf0aacb1747791bba11cdb9fc | 5.53 MiB   |
| SSU-22621.4539-x64.cab                                      | 470d418bad3cca02e12c2aaf3910f416203af410 | 15.31 MiB  |
| Windows11.0-KB5045935-x64-NDP481.cab                        | 44b407deb81aa1e0bced9323c744018fc2beaaa5 | 71.84 MiB  |
| Windows11.0-KB5046732-x64.psf                               | c6a9a9738edc0fe167a8c0f66a40d72ee4218c64 | 685.32 MiB |
| Windows11.0-KB5046732-x64.wim                               | 6a321c6d82f0a5da4ca22b1b2e226267f243df09 | 70 MiB     |
| Windows11.0-KB5046906-x64.cab                               | 34f5e9fd71197827dfd226d1228429beff6e5334 | 17.87 MiB  |
| Windows11.0-KB5046915-x64.cab                               | bad425837da1e63557bf3a96c73fe2e793fc8b7a | 7.72 MiB   |
| f3691231-0586-44d5-859b-e25f5eb9cfb7.AggregatedMetadata.cab | 522d50939c0c33a43fc4ad4b6f466f12e58b2880 | 2.46 MiB   |
| windows11.0-kb5027397-x64.cab                               | 955d24b7a533f830940f5163371de45ff349f8d9 | 33.77 KiB  |

[Windows 11, version 23H2 (22631.4534) amd64](https://uupdump.net/findfiles.php?id=1d9398a5-2b21-469d-a671-797faa004bce&q=!updates)

| File                                                        | SHA-1                                    | Size       |
| ----------------------------------------------------------- | ---------------------------------------- | ---------- |
| 1d9398a5-2b21-469d-a671-797faa004bce.AggregatedMetadata.cab | ac0b47c4d96eaafda1d5f50b16a1e9d8332220da | 2.46 MiB   |
| DesktopDeployment.cab                                       | 31060edf375c59193939bea9cae9fe6e6927a3f9 | 5.53 MiB   |
| SSU-22621.4526-x64.cab                                      | 5276a1aeb2f1f614539f2c7dc2bef30a3e9f9985 | 15.31 MiB  |
| Windows11.0-KB5045935-x64-NDP481.cab                        | 44b407deb81aa1e0bced9323c744018fc2beaaa5 | 71.84 MiB  |
| Windows11.0-KB5046732-x64.cab                               | 28a5cc7eaf8f7f5fd980ad81e6f715247aafe328 | 97.66 MiB  |
| Windows11.0-KB5046732-x64.psf                               | 3d27a59006a4b8ae50b837ac4078f5601484ebe8 | 685.31 MiB |
| Windows11.0-KB5046906-x64.cab                               | 34f5e9fd71197827dfd226d1228429beff6e5334 | 17.87 MiB  |
| Windows11.0-KB5046915-x64.cab                               | bad425837da1e63557bf3a96c73fe2e793fc8b7a | 7.72 MiB   |
| windows11.0-kb5027397-x64.cab                               | 955d24b7a533f830940f5163371de45ff349f8d9 | 33.77 KiB  |

**Comment by abbodi1406** [comment]
I'm aware of that
unfortunately, W10UI can't be used to repack the files as msu

uup-converter already can
if you don't need to use it, you can use PSFX_MSU script to prepare the msu file, which then you can use with W10UI
https://github.com/abbodi1406/WHD/raw/refs/heads/master/scripts/PSFX_MSU_5.zip

you will need LCU WIM+PSF + AggregatedMetadata.cab + DesktopDeployment.cab and/or SSU cab

**Comment by abbodi1406** [comment]
W10UI now include the PSFX_MSU function
