### ISSUE TITLE
Search engine stop working after add LP

### ISSUE THREAD

**Issue by anwar-alsilwy** [abbodi1406/BatUtil#6]
I just added Arabic language ( ar-sa  ) LP with additional OnDemand files (totally 5 files from UUP site) to unmodified win10 build 1909 en-us version, using W10MUI tool + enable .Net 3.5
I followed README instructions step by step.
Arabic language added successfully to setup UI (boot.wim) and whole windows OS.
But I noticed that search engine not responding in start menu and also windows explorer at all.
Any suggestions please.

**Comment by abbodi1406** [comment]
If you use source ISO that contain updates (e.g. 1909 or 20H2), you must add latest cumulative update after adding languages

it's better to start with clean 1903 ISO, add languages, then use W10UI to add updates, including 1909 Enablement package KB4517245

**Comment by anwar-alsilwy** [comment]
Let me know something please:
If I downloaded latest windows update build .iso (e.g 20H2) from MS site, why I should download additional cumulative updates, Beside, LP files version are identical to windows .iso build.
Could you explain to me please

Cheers.

**Comment by abbodi1406** [comment]
LP files are identical to the build RTM number (e.g. 18362.1), they don't change themselves

cumulative update contain the updated language files that match the updated components (e.g. explorer.exe or systemsettings.exe)

it's how Windows works, language packs first then updates, or re-add updates

**Comment by anwar-alsilwy** [comment]
Oh... well
Where can I get this cumulative update files for (e.g 1909 or 20H2), and can I add it to iso using W10UI tool directly after adding LP using W10MUI.

**Comment by abbodi1406** [comment]
https://www.catalog.update.microsoft.com/Search.aspx?q=cumulative+1909
https://www.catalog.update.microsoft.com/Search.aspx?q=cumulative+20H2
click on "Last Updated" to sort by newest update

do not download the .NET cumulative

**Comment by anwar-alsilwy** [comment]
Now it's working fine,
Thanks a lot for instructions,
You are my hero, man.
