### ISSUE TITLE
[QUESTION] Add defender updates

### ISSUE THREAD

**Issue by KesunyianAyam** [abbodi1406/BatUtil#8]
I noticed that in uup-converter that there is a function `:defender_update` that adds ms defender definition and platform updates by setting a certain value in `mpamfe` variable. I wonder how to utilize it because there is no documentation about it inside the readme. Thanks in advance :-)

**Comment by abbodi1406** [comment]
This is imported function of [W10UI](https://github.com/abbodi1406/BatUtil/tree/master/W10UI):
- Added support to integrate Microsoft Defender update (defender-dism-[x86|x64].cab)  
https://support.microsoft.com/en-us/help/4568292

just download and place the defender-dism cab file with other updates files

**Comment by KesunyianAyam** [comment]
Thank you for the information provided :)
